Repository ansible-collections/ansible.utils, pull requests merged in 2024-01, with the labels that each got.

#320 docs: Fixed ipv6form filter document
  changelogs/fragments/ipv6form-doc.yaml
  docs/ansible.utils.ipv6form_filter.rst
  plugins/filter/ipv6form.py
Labels: bug

#325 docs: Fixed validate lookup plugin and module filter examples in document
  changelogs/fragments/validate-doc.yaml
  docs/ansible.utils.validate_lookup.rst
  docs/ansible.utils.validate_module.rst
  plugins/lookup/validate.py
  plugins/modules/validate.py
Labels: bug, documentation

#323 Enhance fact_diff to show common lines
  changelogs/fragments/Fre_fact_diff.yaml
  docs/ansible.utils.fact_diff_filter.rst
  plugins/filter/fact_diff.py
  plugins/plugin_utils/fact_diff.py
  tests/integration/targets/utils_fact_diff/tasks/filter.yaml
  tests/unit/plugins/filter/test_fact_diff.py
Labels: enhancement

#326 Avoid unnecessary use of a persistent connection
  changelogs/fragments/add_require_Connection.yaml
  plugins/action/cli_parse.py
  plugins/action/fact_diff.py
  plugins/action/update_fact.py
  plugins/action/validate.py
Labels: enhancement

#318 [GHA] Update reference for GitHub actions
  .github/workflows/check_label.yml
  .github/workflows/codecoverage.yml
  .github/workflows/draft_release.yml
  .github/workflows/lint.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .github/workflows/token_refresh.yml
  tests/unit/plugins/filter/test_ipaddr.py
  tox-ansible.ini
Labels: skip-changelog

#328 Release 3.1.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/Fre_fact_diff.yaml
  changelogs/fragments/add_require_Connection.yaml
  changelogs/fragments/ipv6form-doc.yaml
  changelogs/fragments/validate-doc.yaml
  galaxy.yml
Labels: skip-changelog
